"""infrastructure inventory and watchdog observations"""
from alembic import op
import sqlalchemy as sa
revision = '692c2fdb78ab'
down_revision = 'c1687848c238'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infrastructure_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('builder_id', sa.Integer(), nullable=True),
    sa.Column('node', sa.String(), nullable=True),
    sa.Column('vm_id', sa.Integer(), nullable=True),
    sa.Column('desired_power', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['builder_id'], ['builder_vms.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('builder_id')
    )
    op.create_table('monitor_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('probe_kind', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('freshness_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['infrastructure_resources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'probe_kind')
    )
    op.create_table('monitor_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['check_id'], ['monitor_checks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitor_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitor_observations_check_id'), ['check_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitor_observations_observed_at'), ['observed_at'], unique=False)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitor_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitor_observations_observed_at'))
        batch_op.drop_index(batch_op.f('ix_monitor_observations_check_id'))

    op.drop_table('monitor_observations')
    op.drop_table('monitor_checks')
    op.drop_table('infrastructure_resources')
    # ### end Alembic commands ###
