"""future infrastructure incidents and recovery action records"""
from alembic import op
import sqlalchemy as sa
revision = '693d0a3bb924'
down_revision = '9175a26a6c68'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infrastructure_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.Integer(), nullable=True),
    sa.Column('repair_id', sa.Integer(), nullable=True),
    sa.Column('signature', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['check_id'], ['monitor_checks.id'], ),
    sa.ForeignKeyConstraint(['repair_id'], ['repairs.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['infrastructure_resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recovery_action_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('verification_result', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['infrastructure_incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recovery_action_records')
    op.drop_table('infrastructure_incidents')
    # ### end Alembic commands ###
