"""expected infrastructure state and integration events"""
from alembic import op
import sqlalchemy as sa
revision = '9175a26a6c68'
down_revision = '692c2fdb78ab'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('domain_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domain_events_event_type'), ['event_type'], unique=False)

    with op.batch_alter_table('infrastructure_resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_state', sa.String(), nullable=False))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('infrastructure_resources', schema=None) as batch_op:
        batch_op.drop_column('expected_state')

    with op.batch_alter_table('domain_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domain_events_event_type'))

    op.drop_table('domain_events')
    # ### end Alembic commands ###
