"""project scoped reporting credentials"""
from alembic import op
import sqlalchemy as sa
revision = 'a4087e05fc1b'
down_revision = '693d0a3bb924'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('token_digest', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_digest')
    )
    with op.batch_alter_table('report_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_credentials_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_credentials_project_id'))

    op.drop_table('report_credentials')
    # ### end Alembic commands ###
