"""initial conductor state"""
from alembic import op
import sqlalchemy as sa
revision = 'c1687848c238'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('repository', sa.String(), nullable=False),
    sa.Column('production_branch', sa.String(), nullable=False),
    sa.Column('production_server', sa.String(), nullable=False),
    sa.Column('application_path', sa.String(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('health_endpoint', sa.String(), nullable=False),
    sa.Column('production_database_ref', sa.String(), nullable=False),
    sa.Column('test_database_ref', sa.String(), nullable=False),
    sa.Column('migration_directory', sa.String(), nullable=False),
    sa.Column('deployment_policy', sa.String(), nullable=False),
    sa.Column('automatic_repair', sa.Boolean(), nullable=False),
    sa.Column('production_commit', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('builder_vms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('vm_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('node', sa.String(), nullable=False),
    sa.Column('power_state', sa.String(), nullable=False),
    sa.Column('readiness', sa.String(), nullable=False),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('last_final_sync', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id'),
    sa.UniqueConstraint('vm_id')
    )
    op.create_table('project_migrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('migration_number', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('release_commit', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'migration_number')
    )
    op.create_table('repairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('error_signature', sa.String(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=False),
    sa.Column('component', sa.String(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('production_release', sa.String(), nullable=False),
    sa.Column('production_commit', sa.String(), nullable=True),
    sa.Column('builder_commit', sa.String(), nullable=True),
    sa.Column('correlation_ids', sa.Text(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('builder_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['builder_id'], ['builder_vms.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alpha_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repair_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repair_id'], ['repairs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repair_id')
    )
    op.create_table('releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('repair_id', sa.Integer(), nullable=True),
    sa.Column('builder_id', sa.Integer(), nullable=True),
    sa.Column('release_number', sa.String(), nullable=False),
    sa.Column('commit', sa.String(), nullable=False),
    sa.Column('previous_commit', sa.String(), nullable=True),
    sa.Column('migration_start', sa.Integer(), nullable=True),
    sa.Column('migration_end', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('health_result', sa.String(), nullable=False),
    sa.Column('restoration_status', sa.String(), nullable=False),
    sa.Column('final_sync_status', sa.String(), nullable=False),
    sa.Column('failure', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['builder_id'], ['builder_vms.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['repair_id'], ['repairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    op.execute("INSERT INTO alpha_slot (id, repair_id) VALUES (1, NULL)")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('releases')
    op.drop_table('alpha_slot')
    op.drop_table('repairs')
    op.drop_table('project_migrations')
    op.drop_table('builder_vms')
    op.drop_table('projects')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
